/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CBS.view.LoginForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginForm',

    requires: [
        'CBS.view.LoginFormViewModel',
        'CBS.view.LoginFormViewController',
        'Ext.form.field.Text',
        'Ext.panel.Tool',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    controller: 'loginform',
    viewModel: {
        type: 'loginform'
    },
    modal: true,
    floating: true,
    hidden: true,
    itemId: 'loginForm',
    width: 400,
    animCollapse: true,
    collapsed: false,
    collapsible: false,
    titleCollapse: false,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'textfield',
            margin: 10,
            padding: 10,
            fieldLabel: 'User Name'
        },
        {
            xtype: 'textfield',
            margin: 10,
            padding: 10,
            fieldLabel: 'Password',
            inputType: 'password'
        },
        {
            xtype: 'textfield',
            margin: 10,
            padding: 10,
            fieldLabel: 'Phone',
            bind: {
                hidden: '{!newUser}'
            }
        },
        {
            xtype: 'checkboxfield',
            margin: 10,
            padding: 10,
            fieldLabel: 'Label',
            boxLabel: 'New user ?',
            bind: {
                value: '{newUser}'
            }
        },
        {
            xtype: 'button',
            height: 30,
            margin: 3,
            width: 100,
            text: 'Sign up',
            bind: {
                hidden: '{!newUser}'
            }
        },
        {
            xtype: 'button',
            height: 30,
            margin: 3,
            width: 100,
            text: 'Login',
            bind: {
                hidden: '{newUser}'
            }
        }
    ],
    tools: [
        {
            xtype: 'tool',
            type: 'close',
            listeners: {
                click: 'onToolClick'
            }
        }
    ]

});