/*
 * File: app/view/RegistrationForm.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CBS.view.RegistrationForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.registrationForm',

    requires: [
        'CBS.view.Actor.ActorDetailsViewModel1',
        'CBS.view.Actor.ActorDetailsViewController1',
        'Ext.form.FieldSet',
        'Ext.form.field.Number',
        'Ext.button.Button',
        'Ext.form.field.File'
    ],

    controller: 'registrationform',
    viewModel: {
        type: 'registrationform'
    },
    padding: 10,
    layout: 'table',
    bodyPadding: 10,

    items: [
        {
            xtype: 'fieldset',
            colspan: 5,
            height: 450,
            margin: 10,
            width: 450,
            title: 'Actor Details',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    margin: 15,
                    width: 300,
                    fieldLabel: 'Name',
                    bind: {
                        value: '{actor.actorName}'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    margin: 15,
                    width: 300,
                    fieldLabel: 'Gender',
                    bind: {
                        value: '{actor.actorGender}'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    margin: 15,
                    width: 300,
                    fieldLabel: 'Age',
                    bind: {
                        value: '{actor.actorAge}'
                    }
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    margin: 15,
                    width: 300,
                    fieldLabel: 'Contact Number',
                    bind: {
                        value: '{actor.contactNumber}'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    margin: 15,
                    width: 300,
                    fieldLabel: 'Work Profile',
                    bind: {
                        value: '{actor.workProfile}'
                    }
                },
                {
                    xtype: 'component',
                    autoEl: {
                        tag: 'input',
                        type: 'file',
                        multiple: true,
                        accept: 'image/*'
                    },
                    hidden: true,
                    id: 'profileImageUpload',
                    itemId: 'fileUpload',
                    listeners: {
                        render: 'onProfileImageUploadRender'
                    }
                },
                {
                    xtype: 'button',
                    hidden: true,
                    margin: '0 0 0 250',
                    text: 'Upload Photos',
                    listeners: {
                        click: 'onButtonClick'
                    }
                },
                {
                    xtype: 'filefield',
                    multi: true,
                    margin: 15,
                    width: 300,
                    fieldLabel: 'Profile Images',
                    listeners: {
                        change: 'onFilefieldChange'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'border-box',
            height: 450,
            id: 'uploadedImages',
            itemId: 'uploadedImages',
            maxWidth: 350,
            scrollable: true
        }
    ]

});