/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CBS.view.Viewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.viewport',

    requires: [
        'CBS.view.ViewportViewModel',
        'CBS.view.Common.MenuBar',
        'Ext.container.Container',
        'Ext.Img',
        'Ext.toolbar.Spacer'
    ],

    viewModel: {
        type: 'viewport'
    },
    cls: 'page-background',
    itemId: 'viewport',

    items: [
        {
            xtype: 'container',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'image',
                    height: 60,
                    width: 180,
                    imgCls: 'brand-logo',
                    src: 'resources/images/brand-logo.jpg'
                },
                {
                    xtype: 'tbspacer',
                    flex: 8
                },
                {
                    xtype: 'component',
                    flex: 1,
                    html: '<a href="#register">Register</a>'
                }
            ]
        },
        {
            xtype: 'menuBar'
        },
        {
            xtype: 'container',
            id: 'mainContainer',
            itemId: 'mainContainer',
            layout: 'fit',
            items: [
                {
                    xtype: 'component',
                    itemId: 'displayBoard'
                }
            ]
        }
    ]

});