/*
 * File: app/model/ActorModel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CBS.model.ActorModel', {
    extend: 'Ext.data.Model',
    alias: 'model.actormodel',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer'
    ],

    fields: [
        {
            name: 'actorId'
        },
        {
            type: 'string',
            name: 'actorName'
        },
        {
            type: 'string',
            name: 'actorGender'
        },
        {
            calculate: function(data) {
                return 'resources/images/ActorPhotos/'+data.actorId+'.jpg';
            },
            name: 'actorPhoto'
        },
        {
            type: 'string',
            name: 'actorAge'
        },
        {
            type: 'int',
            name: 'contactNumber'
        },
        {
            type: 'string',
            name: 'workProfile'
        }
    ]
});