/*
 * File: app/view/Actor/ActorDetailsViewController1.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CBS.view.Actor.ActorDetailsViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.registrationform',

    loadImages: function(files) {
        console.log(files);
        var reader = new FileReader();
        var ls=localStorage;
        var me=this.getView();
        var con=Ext.getCmp('uploadedImages');
        if(files.length>0){
            for(i=0;i<files.length;i++){
            var img= {
                xtype:'image',
                src:window.URL.createObjectURL(files[i]),
                cls:'img-detail'
            };
            con.add(img);
            }

        }
    },

    onProfileImageUploadRender: function(component, eOpts) {
        var me=this;
        component.getEl().on('change',function(evt){
            me.loadImages(evt.target.files);
        });
    },

    onButtonClick: function(button, e, eOpts) {
        var uploadEl= Ext.getDom('profileImageUpload');
        uploadEl.click();
    },

    onFilefieldChange: function(filefield, value, eOpts) {
        this.loadImages(filefield.fileInputEl.dom.files);
    }

});
