/*
 * File: app/view/Actor/ActorDetails.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CBS.view.Actor.ActorDetails', {
    extend: 'Ext.form.Panel',
    alias: 'widget.actorDetails',

    requires: [
        'CBS.view.Actor.ActorDetailsViewModel',
        'Ext.Img',
        'Ext.form.FieldSet',
        'Ext.form.field.Display'
    ],

    viewModel: {
        type: 'actor.actordetails'
    },
    padding: 10,
    layout: 'table',
    bodyPadding: 10,

    items: [
        {
            xtype: 'image',
            colspan: 3,
            cls: 'img-detail',
            imgCls: 'img-detail',
            bind: {
                src: '{actor.actorPhoto}'
            }
        },
        {
            xtype: 'fieldset',
            colspan: 5,
            margin: 10,
            title: 'Actor Details',
            items: [
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    margin: 15,
                    width: 300,
                    fieldLabel: 'Name',
                    bind: {
                        value: '{actor.actorName}'
                    }
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    margin: 15,
                    width: 300,
                    fieldLabel: 'Gender',
                    bind: {
                        value: '{actor.actorGender}'
                    }
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    margin: 15,
                    width: 300,
                    fieldLabel: 'Age',
                    bind: {
                        value: '{actor.actorAge}'
                    }
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    margin: 15,
                    width: 300,
                    fieldLabel: 'Contact Number',
                    bind: {
                        value: '{actor.contactNumber}'
                    }
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    margin: 15,
                    width: 300,
                    fieldLabel: 'Work Profile',
                    bind: {
                        value: '{actor.workProfile}'
                    }
                }
            ]
        }
    ]

});