/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CBS.controller.MainController', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.app.route.Route'
    ],

    routes: {
        ':screenName': 'onScreenChange'
    },

    onScreenChange: function(screenName) {
        if(screenName){
            this.addScreen(screenName);
        }
    },

    addScreen: function(screenName) {
        var mc=Ext.first('#mainContainer');
        var component= this.getScreen(screenName);
        var details=Ext.create(component);
        mc.suspendLayouts();
        mc.removeAll();
        mc.add(details);
        mc.resumeLayouts(true);

    },

    getScreen: function(screenName) {
        var screenMap={
            'list':'CBS.view.Actor.ActorsGrid',
            'details':'CBS.view.Actor.ActorDetails',
            'register':'CBS.view.RegistrationForm',
            'home':'CBS.view.Dashboard'
        };
        if(screenMap[screenName]){
            return screenMap[screenName];
        }
        else {
            return screenMap['list'];
        }
    }

});
